name: "Atlan dbt Action"
description: "Whenever you make a change to a dbt model, Atlan will add downstream lineage impact context right in your pull requests."
author: "Atlan"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  ATLAN_API_TOKEN:
    description: "Atlan API token"
    required: true
  ATLAN_INSTANCE_URL:
    description: "Atlan instance URL"
    required: true
  IGNORE_MODEL_ALIAS_MATCHING:
    description: "Ignore model alias matching"
    required: false
    default: false
runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: activity
  color: blue
